name: flutter_app_mab
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.27+1
  location: ^3.0.2
  flutter_staggered_grid_view:
  parse_server_sdk: ^2.1.0
  curved_navigation_bar: ^0.3.7



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/Image/icons8_clinic_64.png
    - assets/Image/bloodmap.ico
    - assets/Image/doctormsap.ico
    - assets/Image/pharmacymap.ico
    - assets/Image/labaratory.jpg
    - assets/Image/center1.jpg
    - assets/Image/center2.jpg
    - assets/Image/center3.jpg
    - assets/Image/center4.jpg
    - assets/Image/center5.jpg
    - assets/Image/center6.jpg
    - assets/Image/center7.jpg
    - assets/Image/children.ico
    - assets/Image/ddoctor.jpg
    - assets/Image/doctor.jpg
    - assets/Image/fdoctor.jpg
    - assets/Image/hearing.ico
    - assets/Image/heart.ico
    - assets/Image/center.jpg
    - assets/Image/menu.png
    - assets/Image/ophthalmology.ico
    - assets/Image/pharmacy.jpg
    - assets/Image/pregnant.ico
    - assets/Image/skin.ico
    - assets/Image/tooth.ico
    - assets/Image/torso.ico
    - assets/Image/hospital.png
    - assets/Image/doctor.ico
    - assets/Image/pharmacy.ico
    - assets/Image/blood.ico

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
